### ISSUE TITLE
[Question] Original \ Modified folder structure

### ISSUE THREAD

**Issue by fvet** [NAVBaaS/GitIntegration#11]
Seems like NAVBaas expects all files to be in the root under the Original or Modified folder (also for the 'Compare' command to work). In the past, we used to create subfolders per object type ('\Codeunits', '\Pages', ...) in our repositories, mainly to improve the speed of loading when browsing through the 'Files' structure on VSTS. What's your experience putting everything in one global folder?

**Comment by fvet** [comment]
Please ignore this issue. Just finished reorganizing my folders on VSTS and speed is acceptable with the git repos.

**Comment by richardrobberse** [comment]
You can also change the original/modified folders by adjusting your user settings.
