### ISSUE TITLE
Clean up temp files after completing 'Create Container'?

### ISSUE THREAD

**Issue by fvet** [NAVBaaS/GitIntegration#12]
[Nice to have] Is there any reason why files used in the 'Create Container' command are not deleted when the command has successfully finished? The bak file (and addins) are moved to C:\Users\xxx\AppData\Local\Temp\CONTAINERNAME and reside there. Our bak files can be quit big and thus take up unnecessary local disk space.

**Comment by richardrobberse** [comment]
They're removed when you remove the container with the remove command because it's not possible to remove a folder that has been mapped to the container.

I'll see if I can remove at leat the files after the container has been created.

**Comment by richardrobberse** [comment]
Fixed in version 1.6.0.
All the files will be removed after the container has been created, the folder structure will be deleted when removing the container through the Remove Container command.
