### ISSUE TITLE
Deletion of objects

### ISSUE THREAD

**Issue by fvet** [NAVBaaS/GitIntegration#13]
NAVBaaS seems not to detect deletion of objects in the Dev env. What's the best practice to manage deletion of objects?

- Delete the object in Dev env and manually delete in the modified folder of the local workspace as well?
- Delete the object in Dev env and create a new object with same ID and name 'Free to use OBJECT ID'?

**Comment by richardrobberse** [comment]
Delete the object from your git repository and commit it, then it'll be deleted from your database as well.

If you delete a modified standard NAV object, it will import the original object from the original folder.

**Comment by fvet** [comment]
Could be interesting to include this kind of scenarios in the readme / wiki? 
I'm sure others will face the same and some basic documentation could avoid these kind of questions.

**Comment by richardrobberse** [comment]
Correct, I'll update the readme.
