### ISSUE TITLE
Extra settings : DefaultBackupFile / DefaultCustomAddins

### ISSUE THREAD

**Issue by fvet** [NAVBaaS/GitIntegration#14]
To ease the setup of a new container, I'd like to provide as much settings as possible in the Workspace settings, so developers would not have to think about where to get the backup / add-ins from. If I could add a default path to our bak / addins (stored on VSTS / DropBox / ...), this could be used in the 'Create Container' command input list.

**Comment by richardrobberse** [comment]
I think it's better that I accept a URL to the bak file during the create container command, you shouldn't store binaries (like bak files) in git.
You could for example use Azure blob storage to store your binaries and create secure URLs that expire over time.
