### ISSUE TITLE
Fix URI creation from path

### ISSUE THREAD

**Issue by aeschli** [NAVBaaS/GitIntegration#16]
In 1.26 we discovered that several extensions call the 'vscode.openFolder' command with invalid file URIs:
- NAVBaaS.git/out/commands/Go.js
  `136,51:             yield vscode.commands.executeCommand('vscode.openFolder', vscode.Uri.parse(gitRepoFolder));`
- NAVBaaS.git/out/commands/openGitRepoFolder.js
  `27,51:             yield vscode.commands.executeCommand('vscode.openFolder', vscode.Uri.parse(gitRepoFolder));`
- NAVBaaS.git/out/commands/openWorkspace.js
  `27,51:             yield vscode.commands.executeCommand('vscode.openFolder', vscode.Uri.parse(gitRepoFolder));`

When creating a URI from a file path, always use `vscode.URI.file(path)`, e.g `vscode.URI.file('c:\\test')`
Use `vscode.URI.parse(uriString)` when the input string is in the form `scheme://authority/path`

See https://github.com/Microsoft/vscode/issues/57267 for more information or for questions.

**Comment by richardrobberse** [comment]
Thanks for letting me know, will fix it asap!

**Comment by richardrobberse** [comment]
Fixed in version 1.6.2, will be on the marketplace within a minute.
