### ISSUE TITLE
User folder with spaces

### ISSUE THREAD

**Issue by Thisha** [NAVBaaS/GitIntegration#18]
Commands do not work as my user folder contains a space.
C:\Users\xxx yyy\.vscode\extensions\navbaas.git-1.6.4...

eg: Go command
_C:\Users\xxx : The term 'C:\Users\xxx' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
error At line:3 char:1
CategoryInfo          : ObjectNotFound: (C:\Users\xxx:String) [], ParentContainsErrorRecordException_

**Comment by richardrobberse** [comment]
When do you get the error?
After choosing your git folder and selecting your license file?

**Comment by Thisha** [comment]
Dear,

Yes, after selecting the license and for the create container command after selecting Cronus/ Bak, I think.

Kind regards.

On Oct 30, 2018 17:11, richardrobberse <notifications@github.com> wrote:

When do you get the error?
After choosing your git folder and selecting your license file?

**Comment by richardrobberse** [comment]
Thanks for your feedback, I'm trying to find a solution right now.

**Comment by richardrobberse** [comment]
I think I've fixed it, please give it another shot.
Just shipped a new version.

**Comment by Thisha** [comment]
Great! It works.
Thank you for the quick response.

**Comment by richardrobberse** [comment]
No problem, I'm glad it's fixed now :) 
Thanks for reporting it.

**Comment by Thisha** [comment]
Could it be there's still one in the additional parameters (-v) for the create container?

On Oct 31, 2018 08:33, richardrobberse <notifications@github.com> wrote:

No problem, I'm glad it's fixed now :)
Thanks for reporting it.

**Comment by richardrobberse** [comment]
You're right, will look at it tonight!
A temp folder is being shared with the container and this temp folder resides within your user's temp folder.

**Comment by richardrobberse** [comment]
Fixed the issue you pointed out, please let me know if any other errors occur because of that path so I can fix them as quickly as possible.

**Comment by Thisha** [comment]
It looks better now but could it be you don't use the useBestContainerOS option as now I have hyperv mentioned in the log and I get a write error with images wich were working using the navcontainerhelper directly.

On Nov 13, 2018 19:31, richardrobberse <notifications@github.com> wrote:

Fixed the issue you pointed out, please let me know if any other errors occur because of that path so I can fix them as quickly as possible.

**Comment by richardrobberse** [comment]
I'm not using that option for sure because it was added way after the development of this extension.
If I implement useBestContainerOS I need to somehow force people to a newer version of the navcontainerhelper, I will definitely look into it.
