### ISSUE TITLE
Permission Error on Creation of Container

### ISSUE THREAD

**Issue by nickrobbo** [NAVBaaS/GitIntegration#6]
Hi, I'm not sure if I should log this here, or in the NAV Container Helper project.
I have the following situation:

- Create container using your command for NAV 2017 CU5 GB.
- Container successfully created checked license is applied in C Side Dev environment.
- Try to open the Web/Windows client and get the following error:
    "You do not have the following permissions on CodeUnit Azure AD User Management: Execute"
- I have checked in SQL and my user is there, with SUPER permissions.

Forgive me if I should have logged this on the NAV Container Helper project and close if this is the case.

**Comment by richardrobberse** [comment]
Hey, this is not related to the navcontainerhelper either but maybe Freddy has an idea.

I can think of two things:
- Your user doesn't have the super permissions, or your super role got corrupt somehow.
- The object is outside of your license, which is most likely the case.

**Comment by nickrobbo** [comment]
Right OK, thanks for getting back to me. It is strange, as the license I am using is the license we are using in our current/live environment..so you would think we would get this error there. I will keep looking. 

Also, just a comment... really enjoyed the webinar you did last week, full of great content.

**Comment by richardrobberse** [comment]
I'm glad you've enjoyed the webinar, thanks!
I'll close the issue here and keep an eye on the other one to see if we can figure it out for you.
