### ISSUE TITLE
Updating control add-ins

### ISSUE THREAD

**Issue by fvet** [NAVBaaS/GitIntegration#8]
When creating a new container, you can specify a folder with the control add-ins. However, when a newer version of control add-ins becomes available, what would be the easiest way to update the control add-ins of an existing container?

Could be interesting having a 'ControlAddins' setting in 'NAVBaaS.Containers' that points to our central add-in location. This, in combination with a 'NAVBaas : Update Add-ins' command that moves the files from the host to the container, would ease the update of the control add-ins to the latest version.

Integration with the 'NAVBaas : Sync' could be interesting as well, to have them automatically updated.

Or do you have any other suggestions?

**Comment by richardrobberse** [comment]
I'll think about it for a while, in the mean time you can use the Copy-FileToNavContainer cmdlet from the navcontainerhelper.
