### ISSUE TITLE
Control add-ins with subfolders

### ISSUE THREAD

**Issue by fvet** [NAVBaaS/GitIntegration#9]
When specifying a 'Control add-ins' folder - that contains several subfolders - during the creation of the container, it seems like the subfolders structure is not maintained when the host files are copied to the container. 

![addins](https://user-images.githubusercontent.com/25268332/44577925-944df180-a792-11e8-9168-051b1b57c26e.png)

Would it be possible to keep the subfolder structure in the container the same to ease future troubleshooting of add-in conflicts?

**Comment by richardrobberse** [comment]
Sounds doable, I'll have a look.

**Comment by richardrobberse** [comment]
Fixed in version 1.6.0.
